### ISSUE TITLE
Ability to disable per request

### ISSUE THREAD

**Issue by leflings** [Setono/client-bundle#2]
Hi!

It would be very nice to have an ability to selectively disable the setting of the client cookie via f.x. route parameters:

```
app_some_route:
    path: /some/very/good/path
    defaults:
        _controller: App\Controller\SomeAction
        _disable_setono_client_id: true
```

and then in `SaveClientIdSubscriber`:
```
        if ($event->getRequest()->attributes->getBoolean('_disable_setono_client_id')) {
            return;
        }
```

**Comment by loevgaard** [comment]
What would be the use case for this? :)

**Comment by leflings** [comment]
Right now it indiscriminately attaches itself to all responses. Admin section, API sections etc. - a lot of places where it's not necessarily needed.

With this change it could be disabled for entire routing sub-sets e.g.:
```yaml
sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing.yml"
    prefix: "%sylius.security.new_api_route%"
    defaults:
        _disable_setono_client_id: true
```

Even better might be selectively enabling it, but perhaps that's another talk :)
